# Generated by Django 4.2.4 on 2023-11-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0002_remove_registerform_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_Name', models.CharField(max_length=250)),
                ('TaskUserID', models.BigIntegerField()),
                ('AssignUserID', models.BigIntegerField()),
            ],
        ),
    ]
