# Generated by Django 4.2.4 on 2023-11-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_projecttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='AssignUserName',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projecttask',
            name='TaskUserName',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
